config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :quotes

  root 'quotes#index'

  get 'quote_preference', to: 'quotes#quote_preference'

  get 'movie_quotes', to: 'quotes#movie_quotes'

  get 'real_life_quotes', to: 'quotes#real_life_quotes'

  get 'tv_show_quotes', to: 'quotes#tv_show_quotes'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :user
  mount_uploader :file, VideoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :quotes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = current_user.quotes.build
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = current_user.quotes.build(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quote_params
      params.require(:quote).permit(:name, :abbreviated_quote, :quote, :file, :genre, :link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/_nav.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<body>
<style>
body {
  font-family: Arial, Helvetica, sans-serif;
}

.navbar {
  overflow: hidden;
  background-color: #333;
}

.navbar a {
  float: left;
  font-size: 16px;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

.dropdown {
  float: left;
  overflow: hidden;
}

.dropdown .dropbtn {
  font-size: 16px;
  border: none;
  outline: none;
  color: white;
  padding: 14px 16px;
  background-color: inherit;
  font-family: inherit;
  margin: 0;
}

.navbar a:hover, .dropdown:hover .dropbtn {
  background-color: red;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f9f9f9;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  float: none;
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
  text-align: left;
}

.dropdown-content a:hover {
  background-color: #ddd;
}

.dropdown:hover .dropdown-content {
  display: block;
}

.topnav {
  overflow: hidden;
  background-color: #333;
}

.topnav a {
  float: left;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.topnav a:hover {
  background-color: #ddd;
  color: black;
}

.topnav a.active {
  background-color: #4CAF50;
  color: white;
}

.topnav-right {
  float: right;
}


</style>
</body>
</head>

<body>

<div class="navbar">
  <%= link_to "Home", root_path, class: "active", id: "myFrame"%>
  <%= link_to "Quote Preference", quote_preference_path, class: "active" %>
  <%= link_to 'New Quote', new_quote_path %>


  <div class="topnav-right">

  <% if user_signed_in? %>

  <!-- <li><%= link_to "Account", edit_user_registration_path %></li> -->
  <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>

  <% else %>

  <li><%= link_to "Sign In", new_user_session_path, class: "active" %></li>

  <% end %>

  </div>

</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quote.com</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <% flash.each do |name, msg| %>
		<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
    <%= yield %>
  </body>
</html>

app/views/quotes/_body.html.erb
<table id="myTable" align="center">
  <thead class="header1">
    <tr class="header">

      <p></p>

      <h1 align="center">
        All Quotes:
      </h1>

      <p></p>

      <th>Quote</th>
      <th>By:</th>
      <th>Genre</th>
      <th>Link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
    <tr>
      <td><%= link_to quote.abbreviated_quote, quote %></td>
      <td><%= quote.name %></td>
      <td><%= quote.genre %></td>
      <td><%= quote.link %></td>
      <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
      <!-- <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
    </tr>
    <% end %>
  </tbody>
</table>

<body>
  <style>
    table, th, td {
      border: 1px solid black;
    }

    table {
      font-family: arial, sans-serif;
      border-collapse: collapse;

    }

    td, th {
      border: 1px solid #000000;
      text-align: left;
      padding: 15px;
    }

    th {
      background-color: #FFFAFA;
    }

    tr {
      background-color: #FFE4B5;
    }

    tr:nth-child(even) {
      background-color: #87CEFA;
    }
  </style>
</body>

app/views/quotes/edit.html.erb
<div class="alert">
  <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
  <strong>Note:</strong> Please Click the Bottom Left Button on the PIN Pad after entering the PIN
</div>

<div class="center1">
  <h2 class="title center2 animated"></h2>
  <div class="center2 pinRC">
    <body>

      <h1>Editing Quote</h1>

      <%= render 'form', quote: @quote %>

      <%= link_to 'Show', @quote %> |
      <%= link_to 'Back', quotes_path %>

      <a class="pinR">
      </a>
    </div>
    <div class="pinC animated">

      <p>
      </p>
    </div>
  </div>


  <body>
    <script>
      jQuery.fn.reverse = [].reverse;

      var PIN = "1248";

      function confirm(pC, pRC, pI, t) {
        var val = pI.attr('pin');
        if (typeof val !== 'undefined' && typeof val !== 'null' && val !== '' && val.length === 4 && val === PIN) {
          pC.removeClass("bounceInUp");
          pC.addClass("bounceOutDown");
          t.removeClass("rubberBand");
          setTimeout(function() {
            pC.hide();
            pRC.fadeIn();
            t.addClass("rubberBand").html('Pin correct! You can now Edit the Quote');
          }, 500);
        } else {
          pC.removeClass("bounceInUp").removeClass("shake");
          setTimeout(function() {
            pC.addClass("shake");
          }, 200);
          pI.children(".pinpart").removeClass("active").removeClass("rubberBand");
          pI.attr('pin', '');
        }
      }

      $(document).ready(function() {
        var pC = $(".pinC");
        var pRC = $(".pinRC");
        var pR = $(".pinR");
        var pI;
        var t = $(".title");



        var xa = 0;
        for (var x = 1; x <= 9; x++) {
          var x2;
          var y1_2 = '',
          y2_2 = '',
          y3_2 = '',
          y4_2 = '';
          if (x > 1) {
            if (x === 2) {
              x2 = x - 1;
            } else {
              x2 = (x) * 3 - (5 - xa);
            }
            if (x === 7) {
              xa = 1;
            }

            var y1 = x2 + 96,
            y2 = y1 + 1,
            y3 = y2 + 1;
            if (x === 7 || x === 9) {
              var y4 = y3 + 1;
              y4_2 = String.fromCharCode(y4);
            }

            y1_2 = String.fromCharCode(y1),
            y2_2 = String.fromCharCode(y2),
            y3_2 = String.fromCharCode(y3);
          }
          var eLe = $('<div class="pinB" nr="'+x+'"><span class="pin_T">'+x+'</span><span class="pin_t">'+y1_2+y2_2+y3_2+y4_2+'</span></div>');
          pC.append(eLe);
        }
        var eLe = $('<div class="pinB input animated" pin=""><span class="pinpart animated"></span><span class="pinpart animated"></span><span class="pinpart animated"></span><span class="pinpart animated"></span></div><div class="pinB" nr="0"><span class="pin_T">0</span><span class="pin_t"></span></div><div class="pinB delete"><span class="pin_T">[X]</span></div>');
        pC.append(eLe);
        pI = pC.find(".pinB.input");
        $(".pinB:not(.empty):not(.input):not(.delete)").on('click', function() {
          var val1 = pI.html();
          var val2 = pI.attr('pin');
          pI.children(".pinpart").removeClass("rubberBand");
          if (val2.length < 4) {
            var vx = 0;
            pI.children(".pinpart").each(function() {
              if (val2.length === vx) {
                $(this).addClass("active").addClass("rubberBand");
              }
              vx++;
            });
            // pI.html(val1 + "* ");
            pI.attr('pin', val2 + $(this).attr("nr"));
            if (pI.attr('pin').length === 4) {
              pI.removeClass("tada").removeClass("jello");
              setTimeout(function() {
                pI.addClass("tada");
                setTimeout(function() {
                  pI.removeClass("tada");
                }, 600);
              }, 200);
            }
          } else {
            pI.removeClass("jello");
            setTimeout(function() {
              pI.addClass("jello");
            }, 200);
          }
          setTimeout(function() {
            pI.children(".pinpart").removeClass("rubberBand");
          }, 400);
        });
        $(".pinB.delete").on('click', function() {
          var val1 = pI.html();
          var val2 = pI.attr('pin');
          pI.removeClass("jello");
          pI.children(".pinpart").removeClass("rubberBand");
          if (typeof val2 !== 'undefined' && typeof val2 !== 'null' && val2 !== '') {
            var vx = 4;
            pI.children(".pinpart").reverse().each(function() {
              if (val2.length === vx) {
                $(this).removeClass("active").addClass("rubberBand");
              }
              vx--;
            });
            // pI.html(val1.slice(0, val1.length - 2));
            pI.attr('pin', val2.slice(0, val2.length - 1));
          }
          setTimeout(function() {
            pI.children(".pinpart").removeClass("rubberBand");
          }, 400);
        });
        pI.on('click', function() {
          pI.children(".pinpart").removeClass("rubberBand");
          confirm(pC, pRC, pI, t);
        });

        pR.on('click', function() {
          pRC.hide();
          pI.children(".pinpart").removeClass("active").removeClass("rubberBand");
          pI.attr('pin', '');
          t.html('Enter Pin to Edit the Quote');
          pC.removeClass("bounceOutDown");
          pC.addClass("bounceInUp");
          pC.show();
        });
        pR.click();
      });
    </script>
  </body>

  <body>
    <style>

      body {
        margin: 0;
      }

      .center1 {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-38%, -50%);
      }
      .center2 {
        text-align: center;
      }

      .pinRC {
        display: none;
      }

      .pinC {
        display: block;
        position: relative;
        width: 255px;
        height: 200px;
      }
      .pinC > .pinB {
        position: relative;
        float: left;
        width: calc(200px / 3);
        height: calc(200px / 3);
        text-align: center;
        line-height: 3;
        -webkit-transition: all 0.2s ease;
        -moz-transition: all 0.2s ease;
        -o-transition: all 0.2s ease;
        transition: all 0.2s ease;
        -webkit-touch-callout: none;
        -webkit-user-select: none;
        -khtml-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }
      .pinC > .pinB:not(.empty) {
        background-color: #dcdcdc;￼
        border: 2px solid #ffffff;
      }
      .pinC > .pinB:not(.empty):hover {
        /*     border: 2px dotted #fefefe; */
        cursor: pointer;
      }
      .pinC > .pinB:not(.empty)::before {
        content: " ";
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(100, 100, 100, 0);
        -webkit-transition: all 0.4s ease;
        -moz-transition: all 0.4s ease;
        -o-transition: all 0.4s ease;
        transition: all 0.4s ease;
        -webkit-touch-callout: none;
        -webkit-user-select: none;
        -khtml-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }
      .pinC > .pinB:not(.empty):active::before {
        background-color: rgba(200, 200, 200, 0.45);
      }
      .pinC > .pinB > .pin_T {
        position: absolute;
        width: 100%;
        left: 0%;
        height: 100%;
      }
      .pinC > .pinB > .pin_t {
        font-size: 75%;
        position: absolute;
        bottom: -5px;
        left: 50%;
        color: darkgrey;
        transform: translate(-50%, 0);
      }

      .pinC > .pinB.input > .pinpart {
        border: 2px solid #000000;
        border-radius: 50%;
        float: left;
        background-color: transparent;
        width: 7px;
        height: 10px;
        position: relative;
        top: calc(50% - 5px);
        margin-left: 4.5px;
        background-color: rgba(100, 100, 100, 0);
        -webkit-transition: all 0.4s ease;
        -moz-transition: all 0.4s ease;
        -o-transition: all 0.4s ease;
        transition: all 0.4s ease;
        -webkit-touch-callout: none;
        -webkit-user-select: none;
        -khtml-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }
      .pinC > .pinB.input > .pinpart.active {
        background-color: #000000;
      }

      .confirmed {
        animation: removec ease-out 1s;
        animation-iteration-count: 1;
        transform-origin: 0% 50%;
        animation-fill-mode: forwards;
        /*when the spec is finished*/
        -webkit-animation: removec ease-out 1s;
        -webkit-animation-iteration-count: 1;
        -webkit-transform-origin: 0% 50%;
        -webkit-animation-fill-mode: forwards;
        /*Chrome 16+, Safari 4+*/
        -moz-animation: removec ease-out 1s;
        -moz-animation-iteration-count: 1;
        -moz-transform-origin: 0% 50%;
        -moz-animation-fill-mode: forwards;
        /*FF 5+*/
        -o-animation: removec ease-out 1s;
        -o-animation-iteration-count: 1;
        -o-transform-origin: 0% 50%;
        -o-animation-fill-mode: forwards;
        /*Not implemented yet*/
        -ms-animation: removec ease-out 1s;
        -ms-animation-iteration-count: 1;
        -ms-transform-origin: 0% 50%;
        -ms-animation-fill-mode: forwards;
        /*IE 10+*/
      }

      @keyframes removec {
        0% {
          opacity: 1;
          transform: translate(0px, 0px) scaleX(1.00);
        }
        20% {
          opacity: 1;
          transform: translate(0px, 10px) scaleX(1.00);
        }
        25% {
          transform: translate(0px, 0px) scaleX(1.00);
        }
        27% {
          opacity: 0;
          transform: translate(0px, 0px) scaleX(0.00);
        }
        100% {
          opacity: 0;
          transform: translate(0px, 0px) scaleX(0.00);
        }
      }

      @-moz-keyframes removec {
        0% {
          opacity: 1;
          -moz-transform: translate(0px, 0px) scaleX(1.00);
        }
        20% {
          opacity: 1;
          -moz-transform: translate(0px, 10px) scaleX(1.00);
        }
        25% {
          -moz-transform: translate(0px, 0px) scaleX(1.00);
        }
        27% {
          opacity: 0;
          -moz-transform: translate(0px, 0px) scaleX(0.00);
        }
        100% {
          opacity: 0;
          -moz-transform: translate(0px, 0px) scaleX(0.00);
        }
      }

      @-webkit-keyframes removec {
        0% {
          opacity: 1;
          -webkit-transform: translate(0px, 0px) scaleX(1.00);
        }
        20% {
          opacity: 1;
          -webkit-transform: translate(0px, 10px) scaleX(1.00);
        }
        25% {
          -webkit-transform: translate(0px, 0px) scaleX(1.00);
        }
        27% {
          opacity: 0;
          -webkit-transform: translate(0px, 0px) scaleX(0.00);
        }
        100% {
          opacity: 0;
          -webkit-transform: translate(0px, 0px) scaleX(0.00);
        }
      }

      @-o-keyframes removec {
        0% {
          opacity: 1;
          -o-transform: translate(0px, 0px) scaleX(1.00);
        }
        20% {
          opacity: 1;
          -o-transform: translate(0px, 10px) scaleX(1.00);
        }
        25% {
          -o-transform: translate(0px, 0px) scaleX(1.00);
        }
        27% {
          opacity: 0;
          -o-transform: translate(0px, 0px) scaleX(0.00);
        }
        100% {
          opacity: 0;
          -o-transform: translate(0px, 0px) scaleX(0.00);
        }
      }

      @-ms-keyframes removec {
        0% {
          opacity: 1;
          -ms-transform: translate(0px, 0px) scaleX(1.00);
        }
        20% {
          opacity: 1;
          -ms-transform: translate(0px, 10px) scaleX(1.00);
        }
        25% {
          -ms-transform: translate(0px, 0px) scaleX(1.00);
        }
        27% {
          opacity: 0;
          -ms-transform: translate(0px, 0px) scaleX(0.00);
        }
        100% {
          opacity: 0;
          -ms-transform: translate(0px, 0px) scaleX(0.00);
        }
      }
    </style>
  </body>

  <body>
    <style>
      .alert {
        padding: 20px;
        background-color: #f44336;
        color: white;
      }

      .closebtn {
        margin-left: 15px;
        color: white;
        font-weight: bold;
        float: right;
        font-size: 22px;
        line-height: 20px;
        cursor: pointer;
        transition: 0.3s;
      }

      .closebtn:hover {
        color: black;
      }
    </style>
  </body>

app/views/quotes/new.html.erb
<div class="alert">
  <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
  <strong>Note:</strong> Please Click the Bottom Left Button on the PIN Pad after entering the PIN
</div>

<div class="center1">
  <h2 class="title center2 animated"></h2>
  <div class="center2 pinRC">

    <h1>New Quote</h1>

    <%= render 'form', quote: @quote %>

    <%= link_to 'Back', quotes_path %>

    <a class="pinR"></a>
  </div>
  <div class="pinC animated">

    <p></p>
  </div>
</div>

<%= render 'quotes/pin' %>

<body>
  <style>
    .alert {
      padding: 20px;
      background-color: #f44336;
      color: white;
    }

    .closebtn {
      margin-left: 15px;
      color: white;
      font-weight: bold;
      float: right;
      font-size: 22px;
      line-height: 20px;
      cursor: pointer;
      transition: 0.3s;
    }

    .closebtn:hover {
      color: black;
    }
  </style>
</body>

app/views/quotes/quote_preference.html.erb
<html>

<h1 align="center">Here are some quotes for you to look at!</h1>
<h2 align="center">Click one of the Circle Buttons to see some Quotes from Movies, TV Shows or Real-Life Quotes!</h2>

<body>
  <div class="center">
    <button type="button" name="button" onclick="location.href='<%= movie_quotes_path() %>';">
      <span class="circle-1 circle">
        <span class="circle-2 circle">
          <span class="circle-3 circle">
            <span class="icon">Movies</span>
          </span>
        </span>
      </span>
    </button>
    <button type="button" name="button" onclick="location.href='<%= tv_show_quotes_path() %>';">
      <span class="circle-1 circle">
        <span class="circle-2 circle">
          <span class="circle-3 circle">
            <span class="icon">TV Show</span>
          </span>
        </span>
      </span>
    </button>
    <button type="button" name="button" onclick="location.href='<%= real_life_quotes_path() %>';">
      <span class="circle-1 circle">
        <span class="circle-2 circle">
          <span class="circle-3 circle">
            <span class="icon">Real-Life</span>
          </span>
        </span>
      </span>
    </button>
  </div>
</body>

<body>
  <style>

    @keyframes pop1 {
      0% {
        transform: scale(0);
      }
      70% {
        transform: scale(1.15);
      }
      100% {
        transform: scale(1);
      }
    }
    button {
      width: 6.5rem;
      height: 6rem;
      border: 0;
      background-color: #99ffff;
      transition: 250ms;
      cursor: pointer;
    }
    button:hover .circle-1, button:focus .circle-1 {
      background-color: #7ad4f8;
    }
    button:nth-child(2) .circle {
      animation-delay: 1000ms;
    }
    button:nth-child(2) .circle-2 {
      animation-delay: 1500ms;
    }
    button:nth-child(2) .circle-3 {
      animation-delay: 1750ms;
    }
    button:nth-child(2) .icon {
      animation-delay: 2250ms;
    }
    button:nth-child(3) .circle {
      animation-delay: 2000ms;
    }
    button:nth-child(3) .circle-2 {
      animation-delay: 2500ms;
    }
    button:nth-child(3) .circle-3 {
      animation-delay: 2750ms;
    }
    button:nth-child(3) .icon {
      animation-delay: 3250ms;
    }
    button:nth-child(4) .circle {
      animation-delay: 3000ms;
    }
    button:nth-child(4) .circle-2 {
      animation-delay: 3500ms;
    }
    button:nth-child(4) .circle-3 {
      animation-delay: 3750ms;
    }
    button:nth-child(4) .icon {
      animation-delay: 4250ms;
    }
    .circle {
      display: flex;
      justify-content: center;
      align-items: center;
    }
    .circle-1 {
      border-radius: 50%;
      width: 6rem;
      height: 6rem;
      background-color: #99ffff;
      transform: scale(0);
      animation: pop1 250ms ease-out forwards;
    }
    .circle-2 {
      width: 5.25rem;
      height: 5.25rem;
      border-radius: 50%;
      background-color: #000;
      transform: scale(0);
      animation: pop1 250ms ease-out 250ms forwards;
    }
    .circle-3 {
      border-radius: 50%;
      width: 3.75rem;
      height: 3.75rem;
      background-color: #fff;
      transform: scale(0);
      animation: pop1 250ms ease-out 500ms forwards;
    }
    .icon {
      transform: scale(0);
      animation: pop1 250ms linear 1000ms forwards;
    }

    .center {
      text-align: center;
      padding: 70px 0;
    }

  </style>
</body>

<p></p>
  <div align="center">
    <img src="https://media.giphy.com/media/HPF2HULclHx9m/giphy.gif" alt="Whoops Image Not Available">
    <img src="https://media.giphy.com/media/3og0IBJugq2uf9lGwg/giphy.gif" alt="Whoops Image Not Available">
    <img src="https://media.giphy.com/media/HPF2HULclHx9m/giphy.gif" alt="Whoops Image Not Available">

  </div>

</html>

app/views/quotes/show.html.erb
<html>
<div class="quote">
  <span class="left">❝</span>
  <blockquote>
    <%= @quote.quote %>
  </blockquote>
  <small><%= @quote.name %></small>
  <span class="right">❞</span>
</div>

<div class="tweets">
  <p align="center">
  <a
  href="https://twitter.com/share"
  class="twitter-share-button"
  data-text = "<%= @quote.quote %> - <%= @quote.name %>"
  data-size="large"
  data-show-count="false">Tweet
  </a> 
  <script async src="https://platform.twitter.com/widgets.js" charset="utf-8">
  </script>
  <p>
</div>

<body>
  <style>
    body {

    justify-content: center;
  }
  .quote {
    text-align: center;
    font-size: 1rem;
    margin: auto;
    padding: 15px;
    border: 2px solid black;
    max-width: 70%;
    position: relative;
    margin-top: 100px;
  }
  blockquote {
    color: black;
    font-style: italic;
    position: relative;
    z-index: 20;
  }
  .left {
    position: absolute;
    top: -50px;
    left: -20px;
    width: 150px;
    text-align: left;
    z-index: 10;
    font-size: 5rem;
    color: #336699;
    line-height: 200px;
  }
  .right {
    position: absolute;
    bottom: -50px;
    right: -20px;
    width: 150px;
    text-align: right;
    z-index: 10;
    font-size: 5rem;
    color: #336699;
    line-height: 200px;
  }
  small {
    font-size: 1.7rem;
    color: #000000;
    position: relative;
    z-index: 20;
  }
  small:before {
    content: "\2014 \0020";
    width: 5px;
  }

  strong {
  display: block;
  margin-left: auto;
  margin-right: auto;
  }

  tweets {
    display: block;
    margin-left: auto;
    margin-right: auto;
  }

  </style>
</body>


<p align="center">
  <strong>Video:</strong>
</p>

<p align="center">
  <video controls width="550" height="320" src="<%= @quote.file %>"></video>
</p>

<p align="center">
  <strong>Genre:</strong>
  <%= @quote.genre %>
</p>


<p align="center">
  <strong>Link:</strong>
  <%= @quote.link %>
</p>

<%= link_to 'Edit', edit_quote_path(@quote) %>
<%= link_to 'Back', quotes_path %>
</html>